import jackDaniel from "@assets/images/product-Img/jackDaniel.png"
// import optigalChicken from "@assets/images/product-Img/optigalChicken.png"
import jackDanielfire from "@assets/images/product-Img/jackDanielfire.png"
import skyyVodaka from "@assets/images/product-Img/skyVodaka.png"

const product = [
    {
        id:1,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:2,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : skyyVodaka,
    },
    {
        id:3,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDanielfire,
    },
    {
        id:4,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : skyyVodaka,
    },
    {
        id:5,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:6,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDanielfire,
    },
    {
        id:7,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:8,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : skyyVodaka,
    },
    {
        id:9,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:10,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDanielfire,
    },
    {
        id:11,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : skyyVodaka,
    },
    {
        id:12,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:13,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:14,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDanielfire,
    },
    {
        id:15,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:16,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:17,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    {
        id:18,
        productName : "jack",
        price : 29.90,
        marketPrice :  32.90,
        weight : "70cl",
        productRate : "42.70/l",
        img : jackDaniel,
    },
    
]

export default product